all: clean directories libProgressBar.a *.h
	copy *.h out\include\ > nul

clean:
	if exist out\ rd /s /q out\ > nul

directories:
	md out\ out\lib\ out\include\ > nul

libProgressBar.a: ProgressBarManager.o
	ar rcs out\lib\libProgressBar.a out\ProgressBarManager.o

ProgressBarManager.o: ProgressBarManager.h ProgressBarManager.cpp
	g++ -c ProgressBarManager.cpp -o out\ProgressBarManager.o